#!/bin/sh
protected_branch='master'

while read localname localhash remotename remotehash
do
	echo $localname
	echo $localhash
	echo $remotename
	echo $remotehash

	echo $localname | grep $protected_branch >  /dev/null

	if test "$?" = "0"
	then
		protectedFound=true
	fi
done

echo $protectedFound
if test "$protectedFound" = "true"
then
	exec git push $1 haha
	echo >&2 "Pushing to master is not allowed. Pushing to haha"
	exit 1
fi

exit 0