#!/bin/sh
protected_branch='master'
redirect_to='haha'

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# echo $current_branch
# echo $1 $2
protectedFound=false
while read localname localhash remotename remotehash
do
	# echo $localname
	# echo $localhash
	echo $remotename
	# echo $remotehash

	echo $remotename | grep $protected_branch >  /dev/null

	if test "$?" = "0"
	then
		protectedFound=true
	fi
done

echo $protectedFound

if test $protectedFound = "true"
then
echo ok
    # echo pushhing
	# exec git push $1 $redirect_to
	# echo >&2 "Pushing to master is not allowed. Pushing to haha"
	# exit 1
fi


echo "protected branch not found"

exit 0